[alembic]
script_location = app/database/migrations
prepend_sys_path = .
sqlalchemy.url = postgresql+psycopg://healthcheck:healthcheck@localhost:5432/healthcheck

[loggers]
keys = root
level = WARN
handlers = console
qualname =

[handlers]
keys = console
class = StreamHandler
args = (sys.stderr,)

[formatters]
keys = generic
format = %(levelname)s %(message)s

[logger_root]
level = WARN
handlers = console
qualname =

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
